@startuml
title Modelo Entidad-Relación - Gestor de Filas Fertya

entity Turno {
  * id_turno : string <<PK>>
  --
  dni : string
  motivoCodigo : string
  codigoVisible : string
  token : string
  estado : string
  createdAt : timestamp
  horaIngreso : timestamp
  horaLlamado : timestamp
  llamadoPor : string
  tokenConsumed : boolean
  tokenCreatedAt : timestamp
  tokenConsumedAt : timestamp
  tokenConsumedBy : string
  id_categoria : string <<FK>>
}

entity Categoria {
  * id_categoria : string <<PK>>
  --
  seq : integer
}

entity Llamada {
  * id_llamada : string <<PK>>
  --
  id_turno : string <<FK>>
  by : string
  at : timestamp
}

' --- Relaciones ---
Categoria ||--o{ Turno : "clasifica"
Turno ||--o{ Llamada : "historial de llamados"

@enduml
